"""axp.cli — end-to-end publisher/host flow through the command line."""

import json

from axp import cli


def test_keygen_validate_sign_verify_target(tmp_path, example, capsys):
    manifest_path = tmp_path / "agent-extension.json"
    key_path = tmp_path / "signing.key"

    assert cli.main(["keygen", "--out", str(key_path)]) == 0
    public_key = capsys.readouterr().out.strip()
    assert public_key.startswith("ed25519:")

    example["signing"] = {"public_key": public_key, "key_id": "cli-test", "next_key": None}
    example.pop("signature", None)
    manifest_path.write_text(json.dumps(example))

    assert cli.main(["validate", str(manifest_path)]) == 1  # signing block without signature
    capsys.readouterr()

    assert cli.main(["sign", str(manifest_path), "--key", str(key_path), "--in-place"]) == 0
    capsys.readouterr()
    assert cli.main(["validate", str(manifest_path)]) == 0
    summary = json.loads(capsys.readouterr().out)
    assert summary["signed"] is True

    assert cli.main(["verify", str(manifest_path)]) == 0
    capsys.readouterr()
    assert cli.main(["verify", str(manifest_path), "--pinned", public_key]) == 0
    capsys.readouterr()

    # Tamper -> verify fails.
    data = json.loads(manifest_path.read_text())
    data["identity"]["version"] = "9.9.9"
    manifest_path.write_text(json.dumps(data))
    assert cli.main(["verify", str(manifest_path)]) == 1
    capsys.readouterr()


def test_keydir_cli(tmp_path, capsys):
    key = "ed25519:" + "A" * 43 + "="
    out = tmp_path / "keys.json"
    assert cli.main(["keydir", "--publisher", "pub.example", "--key", key + "@graph-memory,other",
                     "--revoked", "ed25519:" + "B" * 43 + "=", "-o", str(out)]) == 0
    doc = json.loads(out.read_text())
    assert doc["publisher"] == "pub.example"
    assert doc["keys"][0] == {"public_key": key, "extensions": ["graph-memory", "other"]}
    assert doc["keys"][1]["revoked"] is True
    assert "agent-extension-keys.json" in capsys.readouterr().out
    assert cli.main(["keydir", "--publisher", "pub.example", "--key", "rsa:nope"]) == 1


def test_target_selection_cli(tmp_path, example, capsys):
    manifest_path = tmp_path / "m.json"
    manifest_path.write_text(json.dumps(example))
    assert cli.main(["target", str(manifest_path), "--runtime", "hermes",
                     "--runtime", "posix", "--platform", "linux/amd64"]) == 0
    picked = json.loads(capsys.readouterr().out)
    assert picked["runtime"] == "hermes"
    assert cli.main(["target", str(manifest_path), "--runtime", "openclaw",
                     "--platform", "linux/amd64"]) == 1
    capsys.readouterr()
    # runtime_version constraint on the hermes target (>=0.18 in the example) is honoured.
    assert cli.main(["target", str(manifest_path), "--runtime", "hermes", "--runtime", "posix",
                     "--platform", "linux/amd64", "--runtime-version", "hermes=0.17.9"]) == 0
    assert json.loads(capsys.readouterr().out)["runtime"] == "posix"
    assert cli.main(["target", str(manifest_path), "--runtime", "hermes",
                     "--platform", "linux/amd64", "--runtime-version", "bogus"]) == 2


def test_canonicalize_matches_signing_input(tmp_path, example, capsysbinary):
    from axp import jcs
    manifest_path = tmp_path / "m.json"
    manifest_path.write_text(json.dumps(example))
    assert cli.main(["canonicalize", str(manifest_path)]) == 0
    assert capsysbinary.readouterr().out == jcs.signing_input(example)
    manifest_path.write_text(json.dumps({**example, "x-float": 1.5}))
    assert cli.main(["canonicalize", str(manifest_path)]) == 1


def test_load_errors_exit_with_a_message(tmp_path, capsys):
    import pytest
    with pytest.raises(SystemExit, match="cannot read"):
        cli.main(["validate", str(tmp_path / "missing.json")])
    (tmp_path / "list.json").write_text("[1, 2]")
    with pytest.raises(SystemExit, match="not a JSON object"):
        cli.main(["validate", str(tmp_path / "list.json")])
    (tmp_path / "broken.json").write_text("{not json")
    with pytest.raises(SystemExit, match="cannot read"):
        cli.main(["verify", str(tmp_path / "broken.json")])


def test_sign_to_output_keygen_guard_and_verify_unsigned(tmp_path, example, capsys):
    key_path = tmp_path / "k.key"
    assert cli.main(["keygen", "--out", str(key_path)]) == 0
    public_key = capsys.readouterr().out.strip()
    assert cli.main(["keygen", "--out", str(key_path)]) == 1          # refuses to clobber
    assert "already exists" in capsys.readouterr().err
    assert cli.main(["keygen", "--out", str(key_path), "--force"]) == 0
    capsys.readouterr()

    example["signing"] = {"public_key": public_key, "key_id": "k", "next_key": None}
    example.pop("signature", None)
    src = tmp_path / "in.json"
    out = tmp_path / "out.json"
    src.write_text(json.dumps(example))
    # The key was regenerated by --force: the declared key no longer matches.
    assert cli.main(["sign", str(src), "--key", str(key_path), "-o", str(out)]) == 1
    assert "does not match" in capsys.readouterr().err
    assert cli.main(["keygen", "--out", str(key_path), "--force"]) == 0
    example["signing"]["public_key"] = capsys.readouterr().out.strip()
    src.write_text(json.dumps(example))
    assert cli.main(["sign", str(src), "--key", str(key_path), "-o", str(out)]) == 0
    assert "signed:" in capsys.readouterr().out
    assert "signature" not in json.loads(src.read_text())    # source untouched
    assert cli.main(["verify", str(out)]) == 0
    capsys.readouterr()
    # Verifying the unsigned source is an error, not "INVALID".
    assert cli.main(["verify", str(src)]) == 1
    assert "no signature" in capsys.readouterr().err


def test_validate_origin_derives_a_v02_publisher(tmp_path, example, capsys):
    del example["identity"]["publisher"]
    path = tmp_path / "m.json"
    path.write_text(json.dumps(example))
    assert cli.main(["validate", str(path)]) == 1
    assert "identity.publisher" in capsys.readouterr().err
    assert cli.main(["validate", str(path), "--origin", "pub.example.org"]) == 0
    summary = json.loads(capsys.readouterr().out)
    assert summary["publisher"] == "pub.example.org" and summary["publisher_derived"] is True


def test_version_flag(capsys):
    import pytest
    from axp import __version__
    with pytest.raises(SystemExit) as exc:
        cli.main(["--version"])
    assert exc.value.code == 0
    assert capsys.readouterr().out.strip() == f"axp {__version__}"


def test_verify_keydir_cross_check(tmp_path, example, capsys):
    from axp import signing
    pem = signing.generate_private_key_pem()
    pub = signing.public_key_from_private(pem)
    example["signing"] = {"public_key": pub, "key_id": "k", "next_key": None}
    example.pop("signature", None)
    manifest_path = tmp_path / "m.json"
    manifest_path.write_text(json.dumps(signing.sign_manifest(example, pem)))
    keydir = tmp_path / "keys.json"

    keydir.write_text(json.dumps({"publisher": "ext.example.com",
                                  "keys": [{"public_key": pub, "extensions": ["graph-memory"]}]}))
    assert cli.main(["verify", str(manifest_path), "--keydir", str(keydir)]) == 0
    assert "listed in the publisher key directory" in capsys.readouterr().out

    # Listed for a different extension only -> not listed for this one.
    keydir.write_text(json.dumps({"publisher": "ext.example.com",
                                  "keys": [{"public_key": pub, "extensions": ["other"]}]}))
    assert cli.main(["verify", str(manifest_path), "--keydir", str(keydir)]) == 1
    assert "not listed" in capsys.readouterr().err

    # Directory for another publisher is an error, not a silent mismatch.
    keydir.write_text(json.dumps({"publisher": "evil.example", "keys": [{"public_key": pub}]}))
    assert cli.main(["verify", str(manifest_path), "--keydir", str(keydir)]) == 1
    assert "belongs to" in capsys.readouterr().err

    # A bad signature is reported before the directory is even consulted.
    tampered = json.loads(manifest_path.read_text())
    tampered["identity"]["version"] = "9.9.9"
    manifest_path.write_text(json.dumps(tampered))
    assert cli.main(["verify", str(manifest_path), "--keydir", str(keydir)]) == 1
    assert "INVALID" in capsys.readouterr().out
